apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiapp
  namespace: default
spec:
  selector:
    matchLabels:
      app:  hiapp
  template:
    metadata:
      labels:
        app: hiapp
    spec:
      containers:
      - name: hiapp
        image: leonemoe/hi
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
          - name: POD_OP
            valueFrom:
                fieldRef:
                  fieldPath: status.podIP
