kind: Service
apiVersion: v1
metadata:
  name:  hi-svc
  namespace: default
spec:
  #type: NodePort
  selector:
    app:  hiapp
  ports:
  - port:  80
    targetPort:  3000
    #nodePort: 32001
    protocol: TCP
